name: worlabel_ai_env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.10
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - fastapi
  - uvicorn
  - ultralytics
  - dill
  - boto3
  - python-dotenv
  - locust
  - websockets
